In [ ]:
#NO 1
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataanime.csv')
df.head()

Title  ...                                        Description
0  Fullmetal Alchemist: Brotherhood  ...  "In order for something to be obtained, someth...
1                    Kimi no Na wa.  ...  Mitsuha Miyamizu, a high school girl, yearns t...
2                          Gintama°  ...  Gintoki, Shinpachi, and Kagura return as the f...
3                     Steins;Gate 0  ...  The dark untold story of Steins;Gate that lead...
4                       Steins;Gate  ...  The self-proclaimed mad scientist Rintarou Oka...

[5 rows x 20 columns]

In [ ]:
df.head()

Title  ...                                        Description
0  Fullmetal Alchemist: Brotherhood  ...  "In order for something to be obtained, someth...
1                    Kimi no Na wa.  ...  Mitsuha Miyamizu, a high school girl, yearns t...
2                          Gintama°  ...  Gintoki, Shinpachi, and Kagura return as the f...
3                     Steins;Gate 0  ...  The dark untold story of Steins;Gate that lead...
4                       Steins;Gate  ...  The self-proclaimed mad scientist Rintarou Oka...

[5 rows x 20 columns]

In [ ]:
df.tail(3)

Title  ...                                        Description
1560  Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...  ...  Ninjas with bloodline limits begin disappearin...
1561        Persona 4 the Animation: The Factor of Hope  ...  Recap of the entire 25-episode television anim...
1562                                       Re:␣Hamatora  ...  It has been three months since the incident at...

[3 rows x 20 columns]

In [ ]:
df.index

RangeIndex(start=0, stop=1563, step=1)

In [ ]:
df.columns

Index(['Title', 'Type', 'Episodes', 'Status', 'Start airing', 'End airing',
       'Starting season', 'Broadcast time', 'Producers', 'Licensors',
       'Studios', 'Sources', 'Genres', 'Duration', 'Rating', 'Score',
       'Scored by', 'Members', 'Favorites', 'Description'],
      dtype='object')

In [ ]:
df.describe()

Score      Scored by       Members     Favorites
count  1563.000000    1563.000000  1.563000e+03    1563.00000
mean      7.905144   60537.209213  1.153567e+05    2309.15483
std       0.340127   99856.869169  1.669685e+05    7358.06195
min       7.480000     144.000000  7.810000e+02       1.00000
25%       7.630000    6876.000000  1.738050e+04      54.00000
50%       7.820000   24730.000000  5.209700e+04     264.00000
75%       8.110000   68933.500000  1.367520e+05    1273.00000
max       9.250000  993775.000000  1.432871e+06  105387.00000

In [ ]:
df.T

0     ...                                               1562
Title                             Fullmetal Alchemist: Brotherhood  ...                                       Re:␣Hamatora
Type                                                            TV  ...                                                 TV
Episodes                                                        64  ...                                                 12
Status                                             Finished Airing  ...                                    Finished Airing
Start airing                                              2009-4-5  ...                                           2014-7-8
End airing                                                2010-7-4  ...                                          2014-9-23
Starting season                                             Spring  ...                                             Summer
Broadcast time                              Sundays at 17:00 (JST)  ...                            Tuesdays at 02:05 (JST)
Producers        Aniplex,Square Enix,Mainichi Broadcasting Syst...  ...  TV Tokyo,Sotsu,AT-X,DAX Production,NAZ,DIVE II...
Licensors                            Funimation,Aniplex of America  ...                                   Sentai Filmworks
Studios                                                      Bones  ...                                             Lerche
Sources                                                      Manga  ...                                           Original
Genres           Action,Military,Adventure,Comedy,Drama,Magic,F...  ...                   Mystery,Comedy,Super Power,Drama
Duration                                           24 min. per ep.  ...                                    24 min. per ep.
Rating                                                           R  ...                                                  R
Score                                                         9.25  ...                                               7.48
Scored by                                                   719706  ...                                              46334
Members                                                    1176368  ...                                              99299
Favorites                                                   105387  ...                                                330
Description      "In order for something to be obtained, someth...  ...  It has been three months since the incident at...

[20 rows x 1563 columns]

In [ ]:
df.sort_index(axis=1, ascending=False)

Type  ...             Broadcast time
0        TV  ...     Sundays at 17:00 (JST)
1     Movie  ...                          -
2        TV  ...  Wednesdays at 18:00 (JST)
3        TV  ...   Thursdays at 01:35 (JST)
4        TV  ...  Wednesdays at 02:05 (JST)
...     ...  ...                        ...
1558     TV  ...                          -
1559    OVA  ...                          -
1560  Movie  ...                          -
1561  Movie  ...                          -
1562     TV  ...    Tuesdays at 02:05 (JST)

[1563 rows x 20 columns]

In [ ]:
df.sort_values(by="Title")

Title  ...                                        Description
1400                   "Bungaku Shoujo" Movie  ...  The protagonist of the story, Konoha Inoue, is...
134                           3-gatsu no Lion  ...  Having reached professional status in middle s...
8                  3-gatsu no Lion 2nd Season  ...  Now in his second year of high school, Rei Kir...
657                                   91 Days  ...  As a child living in the town of Lawless, Ange...
952                   ACCA: 13-ku Kansatsu-ka  ...  ACCA—a national body of the kingdom of Dowa th...
...                                       ...  ...                                                ...
424                                  xxxHOLiC  ...  Kimihiro Watanuki can see spirits and other as...
216                              xxxHOLiC Kei  ...  Kimihiro Watanuki's life was never really norm...
492   xxxHOLiC Movie: Manatsu no Yoru no Yume  ...  Summer break has arrived, but while his other ...
222                              xxxHOLiC Rou  ...  10 years after the events of xxxHOLiC Shunmuki...
348                         xxxHOLiC Shunmuki  ...  For the appropriate price, your dearest wish c...

[1563 rows x 20 columns]

In [ ]:
df.mean()

Score             7.905144
Scored by     60537.209213
Members      115356.738324
Favorites      2309.154830
dtype: float64

In [ ]:
df.mean(1)

0       500367.5625
1       298525.0475
2        67561.0400
3        50016.5400
4       408396.0350
           ...     
1558    118018.6200
1559      4546.1200
1560     41482.3700
1561      3985.3700
1562     36492.6200
Length: 1563, dtype: float64

=================================================================================

In [ ]:
#NO 2
import pandas as pd
import numpy as np
from functools import reduce

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset_uts-2021.csv')
df.head()

No           Name  ...  Project            Email
0   1    Princy Odom  ...   Client  princy@text.com
1   2     Appy Alexa  ...   Client    appy@text.com
2   3      Luna Knox  ...      NaN    luna@text.com
3   4  Clark Andrews  ...   Client   clark@text.com
4   5     Riley Drew  ...  intenal   riley@text.com

[5 rows x 6 columns]

In [ ]:
#a. Menghapus Baris yang berulang
df.drop_duplicates(inplace = True)
print(df.to_string()) 

            Nama                   Alamat Nomor Telepon    Projek            Email
0    Princy Odom        Street 1 New Lane   789456120.0    Client  princy@text.com
1     Appy Alexa                Ac Street   568798821.0    Client    appy@text.com
3  Clark Andrews   PO.BOX 156-Settle Road   123545342.0    Client   clark@text.com
4     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
5    August Bork  PO.BOX 17-Thames Street   125921931.0  Internal     aug@text.com
8    Erica Flint   Street 7 New Lane Road   789456128.0  Internal   erica@text.com


In [ ]:
#b. Menghapus Baris yang hilang (Ada Nilai NaN nya)
df.dropna(inplace = True)

print(df.to_string())

            Nama                   Alamat Nomor Telepon    Projek            Email
0    Princy Odom        Street 1 New Lane   789456120.0    Client  princy@text.com
1     Appy Alexa                Ac Street   568798821.0    Client    appy@text.com
3  Clark Andrews   PO.BOX 156-Settle Road   123545342.0    Client   clark@text.com
4     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
5    August Bork  PO.BOX 17-Thames Street   125921931.0  Internal     aug@text.com
8    Erica Flint   Street 7 New Lane Road   789456128.0  Internal   erica@text.com


In [ ]:
#c. Menghapus kolom yang berisi data yang tidak releva (Hapus Kolom No)
to_drop = ['No']
df.drop(to_drop, inplace = True, axis = 1)
print(df.to_string())

KeyError: ignored

In [ ]:
#d. Perbaiki kesalahan input (intenal harusnya Internal) 
df.loc[4, 'Project'] = 'Internal'
print(df.to_string())

            Name                  Address  Mobile Phone   Project            Email
0    Princy Odom        Street 1 New Lane   789456120.0    Client  princy@text.com
1     Appy Alexa                Ac Street   568798821.0    Client    appy@text.com
3  Clark Andrews   PO.BOX 156-Settle Road   123545342.0    Client   clark@text.com
4     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
5    August Bork  PO.BOX 17-Thames Street   125921931.0  Internal     aug@text.com
6     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
8    Erica Flint   Street 7 New Lane Road   789456128.0  Internal   erica@text.com


In [ ]:
#e. Ubah Tipe data float64 untuk Mobile Phone menjadi Teks atau Object
df = df.astype({"Mobile Phone": str})
df.dtypes

Name            object
Address         object
Mobile Phone    object
Project         object
Email           object
dtype: object

In [ ]:
#f. Ganti nama semua kolom dalam bahasa Indonesia 
df.rename(columns={'Name':'Nama','Address':'Alamat','Mobile Phone':'Nomor Telepon','Project':'Projek'}, inplace=True)
print(df.to_string())

            Nama                   Alamat Nomor Telepon    Projek            Email
0    Princy Odom        Street 1 New Lane   789456120.0    Client  princy@text.com
1     Appy Alexa                Ac Street   568798821.0    Client    appy@text.com
3  Clark Andrews   PO.BOX 156-Settle Road   123545342.0    Client   clark@text.com
4     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
5    August Bork  PO.BOX 17-Thames Street   125921931.0  Internal     aug@text.com
6     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
8    Erica Flint   Street 7 New Lane Road   789456128.0  Internal   erica@text.com


In [ ]:
print(df.to_string())

            Nama                   Alamat Nomor Telepon    Projek            Email
0    Princy Odom        Street 1 New Lane   789456120.0    Client  princy@text.com
1     Appy Alexa                Ac Street   568798821.0    Client    appy@text.com
3  Clark Andrews   PO.BOX 156-Settle Road   123545342.0    Client   clark@text.com
4     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
5    August Bork  PO.BOX 17-Thames Street   125921931.0  Internal     aug@text.com
6     Riley Drew  PO.BOX 16-Thames Street   789821211.0  Internal   riley@text.com
8    Erica Flint   Street 7 New Lane Road   789456128.0  Internal   erica@text.com


===============================================================================================================

In [11]:
#NO 3
import numpy as np

In [12]:
#a
a = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])
print(a)

[[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]


In [39]:
#b
a = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])

b = np.vsplit(a,2)

c = np.array(b)
print(c)

[[[ 5 10 10  7]
  [ 7  8  4 10]
  [ 9 10  2  5]]

 [[ 1  8  9  3]
  [ 6 10  5  2]
  [ 4  6  9  4]]]


In [44]:
#c
a = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])

b = np.vsplit(a,2)

c = np.array(b)

d = np.flipud(c) 

e = np.vstack(d)
print(e)

[[ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]
 [ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]]


In [58]:
#d
a = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])

b = np.vsplit(a,2)

c = np.array(b)

d = np.flipud(c) 

e = np.vstack(d)

f = np.hsplit(e,2)

g = np.array(f)

h = np.fliplr([g])[0]

print(h)


[[[ 9  3]
  [ 5  2]
  [ 9  4]
  [10  7]
  [ 4 10]
  [ 2  5]]

 [[ 1  8]
  [ 6 10]
  [ 4  6]
  [ 5 10]
  [ 7  8]
  [ 9 10]]]


In [59]:
#d
a = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])

b = np.vsplit(a,2)

c = np.array(b)

d = np.flipud(c) 

e = np.vstack(d)

f = np.hsplit(e,2)

g = np.array(f)

h = np.fliplr([g])[0]

i = np.hstack(h)


print(i)


[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
