**LATIHAN**

In [1]:
import numpy as np



---


1. Buatlah array 2d berikut menggunakan numpy





In [8]:
a = np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])
print(a)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]




---
2. Buatlah array 3d berikut menggunakan numpy



In [6]:
a= np.array([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]], #first axis arrays
             [[2,1,2],[9,8,5],[3,7,3],[4,9,9]], #second axis array
             [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]]) #third axis array
# 3-D array
print (a)
print(a.shape)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
(3, 4, 3)




---
3. Tambah angka 1 pada baris ganjil, dan tambah angka 2 pada baris genap



In [42]:
a = np.array([[1,8,8,2],[8,2,1,2],[10,1,4,7],[1,4,7,8],[8,2,3,4]])
print(a, "\n")
print("baris genap:",a[0]+1,a[2]+1,a[4]+1)
print("baris ganjil:",a[1]+2,a[3]+2)


[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]] 

baris genap: [2 9 9 3] [11  2  5  8] [9 3 4 5]
baris ganjil: [10  4  3  4] [ 3  6  9 10]




---
5. ubah array menjadi 2d berukuran 6x6



In [47]:
a= np.array([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]], #first axis arrays
             [[2,1,2],[9,8,5],[3,7,3],[4,9,9]], #second axis array
             [[2,9,3],[2,4,8],[1,6,6],[8,1,3]]]) #third axis array
print(a,"\n")
np.reshape(a,(6,6))

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]] 



array([[ 7,  8,  5,  4,  7,  7],
       [ 7,  1,  9,  5,  4, 10],
       [ 2,  1,  2,  9,  8,  5],
       [ 3,  7,  3,  4,  9,  9],
       [ 2,  9,  3,  2,  4,  8],
       [ 1,  6,  6,  8,  1,  3]])