In [48]:
import sys
#versi python
print("Versi Python = {}".format(sys.version))

Versi Python = 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]


In [49]:
import numpy
#versi numpy
print("Versi Numpy = {}".format(numpy.__version__))

Versi Numpy = 1.19.5


In [50]:
import pandas
#versi pandas
print("Versi Pandas = {}".format(pandas.__version__))

Versi Pandas = 1.1.5


In [51]:
import matplotlib
#versi matplotlib
print("Versi Matplotlib = {}".format(matplotlib.__version__))

Versi Matplotlib = 3.2.2


In [52]:
#membuat dasar numpy array
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [53]:
#array dengan tipe data, gunakan argumen dtype untuk tipe data
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [54]:
#jika nilai array berbeda-beda maka dilakukan upcast, contoh integer menjadi float
np.array([1,2,0,3,4])

array([1, 2, 0, 3, 4])

In [55]:
#array multidimensi
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
#array zeros
np.zeros(5)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
#array ones
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [58]:
#array random
np.random.rand(3,4)

array([[0.29695608, 0.03130016, 0.68201483, 0.75753306],
       [0.42528929, 0.96657707, 0.58357113, 0.36009097],
       [0.19920204, 0.22733458, 0.7791485 , 0.44863604]])

In [59]:
#array buatan sendiri
np.full([2,3],8)

array([[8, 8, 8],
       [8, 8, 8]])

In [60]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])



---


**Pratikum-02.np.arange() method:**
  1. Array berurutan
  2. Array dengan data awal dan akhir dengan jarak yang ditentukan

In [61]:
#array berurutan
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
#Array dengan data awal dan akhir dengan jarak yang ditentukan
np.arange(2,10,3)

array([2, 5, 8])

In [63]:
#array berurutan dengan banyaknya data yang berimbang
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])



---


**Pratikum-03 SHAPE AND RESHAPING NUMPY ARRAY**
  1. Dimensions of NumPy Array
  2. Shape of NumPy Array
  3. Size of NumPy Array 
  4. Reshaping a NumPy Array



In [64]:
#number of axis
a = np.array([[5,10,15],[20,25,20]])
print('Array','\n',a)
print('Dimension','\n',a.ndim)

Array 
 [[ 5 10 15]
 [20 25 20]]
Dimension 
 2


In [65]:
#shape of numpy array
a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows =',a.shape[0])
print('Columns =',a.shape[1])

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows = 2
Columns = 3


In [66]:
#size of numpy array
a = np.array([[5,10,15],[20,25,30]])
print('Ukuran dari array:',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Ukuran dari array: 6
Manual determination of size of array : 6




---


**PRATIKUM-04 Reshaping a NumPy Array**
  1. np.reshape()method, merubah ukuran array tanpa mengubah isi data
  2. mengubah ukuran array, jika tidak pasti kolom atau barisnya beri angka -1
  3. Flattening suatu NumPy array = ubah array jadi 1 dimensi
  4. Transpose Array

In [67]:
#reshape mengubah ukuran array sesuai ukuran yang diinginkan
a = np.array([3,6,9,5,1,2])
np.reshape(a,(2,3))

array([[3, 6, 9],
       [5, 1, 2]])

In [68]:
#mengubah array jika tidak diketahui ukurannya pastinya beri tanda -1
a = np.array([3,6,9,12,18,24])
print('Three Rows :','\n',np.reshape(a,(3,-1)))
print('Three Columns :', '\n',np.reshape(a,(-1,3)))

Three Rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three Columns : 
 [[ 3  6  9]
 [12 18 24]]


In [69]:
#np.ones((2,2))
a = np.array([[3,45,26],[53,51,52],[3,5,6]])
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape setelah flatten :',b.shape)
print('Array :','\n', b)
print('Shape setelah ravel :',c.shape)
print('Array :','\n', c)

Original shape : (3, 3)
Array : 
 [[ 3 45 26]
 [53 51 52]
 [ 3  5  6]]
Shape setelah flatten : (9,)
Array : 
 [ 3 45 26 53 51 52  3  5  6]
Shape setelah ravel : (9,)
Array : 
 [ 3 45 26 53 51 52  3  5  6]


In [70]:
#tranpose array
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print('Original','\n',a.shape,'\n',a)
print('Ukuran array setelah transpose:','\n','Shape',b.shape,'\n',b)

Original 
 (2, 3) 
 [[1 2 3]
 [4 5 6]]
Ukuran array setelah transpose: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]




---


**PRAKTIKUM-05.Indexing dan Slocong of NumPy array**
  1. Slicing 1-D NumPy arrays
  2. Slicing 2-D NumPy arrays
  3. Slicing 3-D NumPy arrays

In [71]:
#Slicing 1-D NumPy arrays
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])

[2 4]


In [72]:
a = np.array([1,2,3,4,5,6])
print(a[1:6:2])

[2 4 6]


In [73]:
a = np.array([1,2,3,4,5,6])
print(a[:6:2]) #tampilkann data dari indeks ke 1 sampai 6 dengan selisih 2
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [74]:
#Slicing 2-D NumPy arrays
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,0]) #baris 0 kolom 0
print(a[1,2])
print(a[1,0])

[[1 2 3]
 [4 5 6]]
1
6
4


In [75]:
a = np.array([[1,2,3],[4,5,6]]) #[baris,kolom]
print(a)
#baris pertama
print('First row value :','\n',a[0:1,:])
#baris pertama dengan step
print('Alternate values from first row:','\n',a[0:1,::2])
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])



[[1 2 3]
 [4 5 6]]
First row value : 
 [[1 2 3]]
Alternate values from first row: 
 [[1 3]]
Second column values : 
 [[2]
 [5]]
Arbitrary values : 
 [[2 3]]


In [76]:
#Slicing 3-D NumPy arrays
a= np.array([[[1,2],[3,4],[5,6]], #first axis arrays
             [[7,8],[9,10],[11,12]], #second axis array
             [[13,14],[15,16],[17,18]]]) #third axis array
# 3-D array
print (a)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)




---


**PRAKTIKUM-5.OPERASI MATEMATIKA**

In [77]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)
print('Subtract :',a-5)
print('Multyply :',a*5)
print('Divide   :',a/5)
print('Power    :',a**2)
print('Remainder:',a%5)

[1 2 3 4 5]
[ 6  7  8  9 10]
Subtract : [-4 -3 -2 -1  0]
Multyply : [ 5 10 15 20 25]
Divide   : [0.2 0.4 0.6 0.8 1. ]
Power    : [ 1  4  9 16 25]
Remainder: [1 2 3 4 0]


In [78]:
a = np.arange(5,15,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.max(np.median(a)))

[ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [79]:
a = np.array([[1,6],[4,3]])
#minimum along a column
print('Min :',np.min(a,axis=0))
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [80]:
a = np.array([[5,6,7,4],[9,2,3,7]]) # sort aling the column
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))

Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]




---


**Pratikum NumPy dengan Dataset**

In [81]:
import csv
with open('/content/drive/MyDrive/Colab Notebooks/winequality-red.csv','r') as f:
  wines = list(csv.reader(f, delimiter=';'))

In [82]:
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [89]:
import numpy as np
wines = np.array(wines[1:], dtype=np.float)


In [90]:
wines.dtype

dtype('float64')

In [91]:
(wines[3:])

array([[11.2  ,  0.28 ,  0.56 , ...,  0.58 ,  9.8  ,  6.   ],
       [ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.4  ,  0.66 ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [93]:
qualities = [float(item[-1]) for item in wines[1:]]
sum(qualities) / len(qualities)

5.636420525657071

In [94]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [95]:
wines.shape

(1599, 12)

In [96]:
wines = np.genfromtxt("/content/drive/MyDrive/Colab Notebooks/winequality-red.csv", delimiter=";", skip_header=1)

In [97]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [98]:
wines[2,3]

2.3

In [99]:
#slicing
wines[0:3,3]

array([1.9, 2.6, 2.3])

In [100]:
wines[:3,3]

array([1.9, 2.6, 2.3])

In [101]:
wines[:,3]

array([1.9, 2.6, 2.3, ..., 2.3, 2. , 3.6])

In [102]:
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])